# Generated by Django 5.0.1 on 2024-01-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mpeso', '0002_alter_userpeso_pesoactual_alter_userpeso_pesoideal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpeso',
            name='altura',
            field=models.IntegerField(default=175),
            preserve_default=False,
        ),
    ]
