# Generated by Django 5.0.1 on 2024-02-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mpeso', '0004_pesoactual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpeso',
            name='pesoActual',
        ),
    ]
